window.teams = [
    // Série A 2025
  { name: "Flamengo", color:"#FF0000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Palmeiras", color:"#008000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "São Paulo", color:"#000000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Corinthians", color:"#000000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Atlético-MG", color:"#000000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Grêmio", color:"#0073CF", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Fluminense", color:"#008000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Internacional", color:"#FF0000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Botafogo", color:"#000000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Fortaleza", color:"#FF0000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Bragantino", color:"#FF0000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Vasco da Gama", color:"#000000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Santos", color:"#FFFFFF", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Cruzeiro", color:"#0000FF", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Athletico-PR", color:"#FF0000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Bahia", color:"#0000FF", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "América-MG", color:"#008000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Coritiba", color:"#008000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Ceará", color:"#000000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Atlético-GO", color:"#FF0000", serie:"A", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },

  // Série B 2025
  { name: "Vila Nova", color:"#0000FF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Guarani", color:"#00FF00", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "CRB", color:"#FF0000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Avaí", color:"#0000FF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "CSA", color:"#FFFFFF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Operário-PR", color:"#008000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Londrina", color:"#0000FF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Sampaio Corrêa", color:"#FF0000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Náutico", color:"#FF0000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Ponte Preta", color:"#000000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Tombense", color:"#008000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Vitória", color:"#FF0000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Ituano", color:"#0000FF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Brasil de Pelotas", color:"#FF0000", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Remo", color:"#0000FF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Cruzeiro B", color:"#0000FF", serie:"B", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },

  // Série C 2025
  { name: "ABC", color:"#FF0000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Botafogo-PB", color:"#000000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Criciúma", color:"#FFAA00", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Paysandu", color:"#008000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Volta Redonda", color:"#0000FF", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Manaus", color:"#00FF00", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Figueirense", color:"#0000FF", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Ypiranga", color:"#FF0000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Santa Cruz", color:"#FF0000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Botafogo-SP", color:"#000000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Ituano C", color:"#FF0000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Sampaio C", color:"#FF0000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Confiança", color:"#0000FF", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
  { name: "Tombense C", color:"#008000", serie:"C", players: [], points:0, games:0, wins:0, draws:0, losses:0, goalsFor:0, goalsAgainst:0, history:[] },
];

